import Head from 'next/head'
import Image from 'next/image'
import banner from '../../assets/banner.png'
import Link from 'next/link';
import { useState } from 'react';
import { MongoClient } from 'mongodb';





 const  Home = ({data})=> {


  return (
    <>
      <Head>
        <title>Carephone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
      <a href="" className="p-10 flex items-center  bg-slate-50 h-11">
        <span className="self-center text-xl font-extrabold whitespace-nowrap text-blue-700 bg-slate-50">CAREPHONE
        </span>
        </a>
      </nav>

<section>

  <div className='banner'>
  <div className="flex items-center justify-center h-screen p-0 text-center flex-col ">
    <h1 className='text-blue-700 font-extrabold text-4xl leading-normal'>EMPOWER YOUR MOBILE EXPERIENCE WITH THE PERFECT ACCESSORIES</h1>
  </div>
  </div>
</section>
<div className="bg-white">
  <div className="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
    <h2 className="text-2xl font-bold tracking-tight text-gray-900">Mobile Accessories</h2>
    <div className="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
    {
      data.map(value => {
        return(
          <>
          <div>
               <Link href={`/${value.slug}`}>
      <div className="group relative">
        <div className="min-h-80 aspect-h-1 aspect-w-1 w-full overflow-hidden rounded-md bg-gray-200 lg:aspect-none group-hover:opacity-75 lg:h-80">
          <img src={value.image} alt="Front of men&#039;s Basic Tee in black." className="h-full w-full object-cover object-center lg:h-full lg:w-full"/>
        </div>
        <div className="mt-4 flex justify-between">
          <div>
            <h3 className="text-sm text-gray-700">
              <div className='font-medium' >
                <span aria-hidden="true" className="absolute inset-0 ">
                <p className="mt-1 text-sm text-stone-50 w-20 pl-2 bg-red-600">HOT SALE</p>

                </span>
                 {value.title}          
                </div>
            </h3>
            <p className="mt-1 text-sm text-gray-500">{value.color}</p>
          </div>
          <p className="text-sm font-medium text-gray-900 pl-2">{value.price}</p>
        </div>
      </div>
                    </Link>
                    </div>
          </>
        )
      })
    }
    </div>





    </div>


</div>




    </>
  )
}

export default Home;


async function getData() {
  const client = await MongoClient.connect("mongodb+srv://umer:niko12345@cluster0.5i8um.mongodb.net/?retryWrites=true&w=majority");
  const db = client.db('carefone');
  const data = await db.collection('products').find().toArray();
  client.close();
 console.log(data)
  return data;
}

export const getServerSideProps = async () => {
  const data = await getData()

  return { props: {data : JSON.parse(JSON.stringify(data))} };
};